spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/db0?serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
        initial-size: 20
        max-active: 100
        min-idle: 5
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 30000
        validation-query: SELECT 'x'
        filters: stat,slf4j
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        stat-view-servlet:
          enabled: false
        web-stat-filter:
          enabled: false

    sharding:
      tables:
        city:
          actual-data-nodes: ds0.city_${0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: city_${id%2}
          key-generator:
            type: SNOWFLAKE
            column: id
    props:
      sql:
        show: true

mybatis:
  mapper-locations: classpath:mapper/**.xml
